/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as VendorRouteImport } from './routes/vendor'
import { Route as CallVendorIdRouteImport } from './routes/call.$vendorId'
import { Route as CopyTicketIdRouteImport } from './routes/copy.$ticketId'
import { Route as TicketTicketIdRouteImport } from './routes/ticket.$ticketId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorRoute = VendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const CallVendorIdRoute = CallVendorIdRouteImport.update({
  id: '/call/$vendorId',
  path: '/call/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyTicketIdRoute = CopyTicketIdRouteImport.update({
  id: '/copy/$ticketId',
  path: '/copy/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketTicketIdRoute = TicketTicketIdRouteImport.update({
  id: '/ticket/$ticketId',
  path: '/ticket/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vendor': typeof VendorRoute
  '/call/$vendorId': typeof CallVendorIdRoute
  '/copy/$ticketId': typeof CopyTicketIdRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vendor': typeof VendorRoute
  '/call/$vendorId': typeof CallVendorIdRoute
  '/copy/$ticketId': typeof CopyTicketIdRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vendor': typeof VendorRoute
  '/call/$vendorId': typeof CallVendorIdRoute
  '/copy/$ticketId': typeof CopyTicketIdRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/vendor'
    | '/call/$vendorId'
    | '/copy/$ticketId'
    | '/ticket/$ticketId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/vendor'
    | '/call/$vendorId'
    | '/copy/$ticketId'
    | '/ticket/$ticketId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/vendor'
    | '/call/$vendorId'
    | '/copy/$ticketId'
    | '/ticket/$ticketId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  VendorRoute: typeof VendorRoute
  CallVendorIdRoute: typeof CallVendorIdRoute
  CopyTicketIdRoute: typeof CopyTicketIdRoute
  TicketTicketIdRoute: typeof TicketTicketIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor': {
      id: '/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$vendorId': {
      id: '/call/$vendorId'
      path: '/call/$vendorId'
      fullPath: '/call/$vendorId'
      preLoaderRoute: typeof CallVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy/$ticketId': {
      id: '/copy/$ticketId'
      path: '/copy/$ticketId'
      fullPath: '/copy/$ticketId'
      preLoaderRoute: typeof CopyTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ticketId': {
      id: '/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/ticket/$ticketId'
      preLoaderRoute: typeof TicketTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  VendorRoute: VendorRoute,
  CallVendorIdRoute: CallVendorIdRoute,
  CopyTicketIdRoute: CopyTicketIdRoute,
  TicketTicketIdRoute: TicketTicketIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
